fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    registration:
      confirmation:
        enabled: false
    from_email:
      address: "%mailer_user%"
      sender_name: "%mailer_user%"
