fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path: /
    controller: App\Controller\MainController::index
take_survey:
  path: /survey/
  controller: App\Controller\MainController::takeSurvey
