fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path: /
    controller: App\Controller\MainController::index
take_survey:
  path: /survey/
  controller: App\Controller\MainController::takeSurvey
show_last_survey_stats:
  path: /survey/stats/
  controller: App\Controller\MainController::showLastStats

admin_user_last_survey_stats:
  path: /admin/userstats/
  controller: App\Controller\MainController::userStatistics
